### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by frehberlik** [Galactic-Cat/d2-attention-test#1]
Its not working without firebase could you please remove the firebase requirement.

**Comment by Galactic-Cat** [comment]
Hey, I've updated a version with all firebase items disabled to a new branch [no-firebase](https://github.com/Galactic-Cat/d2-attention-test/tree/no-firebase), you might want to use that. It's a dirty disable, it's still full of references to it, but it should be error-free.

I designed this quite a while back, and while it still works I've long departed from this coding style (a.k.a. no-style messy code). This is also why I won't clean up the code further, as this project has long been finished for me.

Also I've noted that it uses a webkit-only function to go fullscreen, so it has to be run in a [webkit browser](https://en.wikipedia.org/wiki/List_of_web_browsers#WebKit-based).

Hope it helps.

**Comment by frehberlik** [comment]
Excellent. Thanks a lot.
